### ISSUE TITLE
Issues with the order extends work

### ISSUE THREAD

**Issue by DannyBen** [magynhard/yaml_extend#5]
As I understand, `extends` seems to add the extended files at the *end* of the main file, and not at the *beginning*.

This is a little counter intuitive (since everywhere else, extend or include means "first use the content of the included file"), and causes issues when using anchors.

Example use case:

This is a valid YAML:

```yaml
one: &one
  hello: world

menu:
  <<: *one
```

While this is not a valid YAML:

```
menu:
  <<: *one

one: &one
  hello: world
```

So, if I wish to provide "blocks of YAML" that can be used by other blocks, I cannot use the extend functionality. The below example is broken:

```ruby
# test.rb
require 'yaml_extend'
data = YAML.ext_load_file 'not-works.yml'
puts data.to_yaml
```

```yaml
# child.yml
extends:
- parent.yml

menu:
  <<: *one
  <<: *two
```

```yaml
# parent.yml
one: &one
  hello: world

two: &two
  hi: world
  hey: world
```

I know there are other ways around it, but my use case was more naturally implemented with anchors, and now I know they cannot be used this way.

Is there any reason for the included content to come last and not first?
